name: Format Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Install dos2unix
        run: sudo apt-get install -y dos2unix

      - name: Format Go code
        run: |
          find . -name "*.go" -type f -exec gofmt -w {} \;

      - name: Configure Git
        run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - name: Convert CRLF to LF
        run: |
          find . -type f -not -path "./.git/*" -exec dos2unix {} \;

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: format code and normalize line endings"
          branch: ${{ github.head_ref }}
